spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/guli_pms

  #    url: jdbc:mysql://localhost:3306/guli_pms
#    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: gmall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.0.84
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #  配置主键自增
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 10000

logging:
  level:
    com.coolfish.gmall.product: debug
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#配置线程池
gmall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10
